version: '2'

volumes:
  config: 
  data: 
  logs: 

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
      GITLAB_ROOT_PASSWORD: 'password'
      GITLAB_ROOT_EMAIL: 'n_hime_love@yahoo.co.jp'
    ports:
      - '8080:80'
      - '8443:443'
      - '22:22'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'

