version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/data/html:/var/www/html

  pytest:
    build:
      context: test
    volumes:
      - ./test:/test
    links:
      - "web"
