version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: up
            command: |
                docker-compose -f ./docker-compose.yml up -d web
  test:
    machine: true
    steps:
      - checkout
      - run:
            name: test
            commend: |
                docker-compose -f .docker-compose.yml up -d pytest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test
          requires:
            - build
