version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: up
            command: |
                docker-compose -f ./docker-compose.yml up -d web
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: test
            command: |
                docker-compose -f ./docker-compose.yml up -d pytest
                docker-compose -f ./docker-compose.yml logs pytest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
