version: 2
jobs:
  build:
          #machine: true
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
            name: docker-compose buid
            command: |
                docker-compose -f ./docker-compose.yml build
      - run:
            name: docker-compose up
            command: |
                docker-compose -f ./docker-compose.yml up -d web
      - run:
            name: test
            command: |
                docker-compose -f ./docker-compose.yml up -d pytest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


