version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
                pip install pytest requests
                docker-compose -f ./nginx/docker-compose.yml up -d
      - run:
            name: Test
            command: |
                pytest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


