version: 2
jobs:
  build:
    machine: true 
    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
                python3 -m pip install -r requirements.txt
                docker-compose -f ./nginx/docker-compose.yml up -d
                pytest
