version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
            #- run:
            #name: docker-compose buid
            #command: |
            #    docker-compose build
      - run:
            name: docker-compose up
            command: |
                docker-compose up
                #- run:
                #name: test
                #command: |
                #docker-compose up -d pytest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


