version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
                docker-compose -f ./nginx/docker-compose.yml up nginx -d
      - run:
            name: test
            command: |
                docker-compose -f ./nginx/docker-compose.yml up pytest -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


