version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run:
            name: docker-compose up
            command: |
                docker-compose -f ./docker-compose.yml up
                #- run:
                #name: test
                #command: |
                #docker-compose up -d pytest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


