version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
            name: docker-compose buid
            command: |
                docker-compose build
      - run:
            name: docker-compose up
            command: |
                docker-compose up
                #- run:
                #name: test
                #command: |
                #docker-compose up -d pytest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


